version: "3.1"

services:

  proxy:
    image: gasparandr/scrumbs-proxy
    depends_on:
      - app
      - website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker-volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/fullchain.pem:/etc/letsencrypt/live/scrumbs.app/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/privkey.pem:/etc/letsencrypt/live/scrumbs.app/privkey.pem
      #for certbot challenges
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  app:
    image: gasparandr/scrumbs-app
    depends_on:
      - mongo
    environment:
      - JWT_SECRET=<JWT_SECRET>
      - SUPPORT_EMAIL_ADDRESS=<SUPPORT_EMAIL_ADDRESS>
      - SUPPORT_EMAIL_PW=<SUPPORT_EMAIL_PW>
      - TRELLO_API_KEY=<TRELLO_API_KEY>
      - TRELLO_SECRET=<TRELLO_SECRET>
      - TRELLO_TOKEN=<TRELLO_TOKEN>
      - TRELLO_BUGS_LIST_ID=<TRELLO_BUGS_LIST_ID>
      - TRELLO_FEATURES_LIST_ID=<TRELLO_FEATURES_LIST_ID>

  website:
    image: gasparandr/scrumbs-website
    depends_on:
      - mongo
    environment:
      - ADMIN_SECRET=<ADMIN_SECRET>
      - ADMIN_EMAIL_ADDRESS=<ADMIN_EMAIL_ADDRESS>
      - SUPPORT_EMAIL_ADDRESS=<SUPPORT_EMAIL_ADDRESS>
      - SUPPORT_EMAIL_PW=<SUPPORT_EMAIL_PW>
      - MAILCHIMP_KEY=<MAILCHIMP_KEY>

  mongo:
    image: mongo
    volumes:
      - /docker-volumes/data/mongo:/data/db
